### ISSUE TITLE
Improved text translations

### ISSUE THREAD

**Issue by defunctl** [miiitaka/wp-structuring-markup#100]
Hey @miiitaka,

Some of the wording is a bit confusing, can you tell me the meaning so we can update your text:
![schema_eng](https://cloud.githubusercontent.com/assets/1066195/12875213/0eab99a8-cd9a-11e5-961f-3b4ef064263e.png)

1) Top page: I think you mean Homepage, right? e.g. https://twentysixteendemo.wordpress.com/
2) Post page: This is all post templates, right? e.g. https://twentysixteendemo.wordpress.com/2015/11/30/come-sail-away-with-me/ ?
3) Fixed page: I don't understand what this does. Can you explain?

**Comment by miiitaka** [comment]
Hi @defunctl ,

1) Top Page is the meaning of the Homepage. Towards the Homepage Do is common in foreign countries?
2) Post page → single.php template.
3) Fixed page → page.php template.

I'm afraid that my comment have some mistakes because I'm not at English.
If you find them,please point out my mistakes.
I can learn a lot from hearing that

**Comment by defunctl** [comment]
Sorry for the delay, and no problem! Happy to help.

Let's go with this:

1) Output Page: → Output On:
2) All Page → All Pages (In Header)
3) Top Page → Homepage
4) Post Page → Posts
5) Fixed Page → Pages

**Comment by miiitaka** [comment]
version2.4.1 Release.
https://github.com/miiitaka/wp-structuring-markup/pull/103
