### ISSUE TITLE
Set thumbnail images manually

### ISSUE THREAD

**Issue by miiitaka** [miiitaka/wp-structuring-markup#233]
Added custom field so that thumbnail images can be set manually.

**Comment by TekstP** [comment]
Thx for adding this issue that is due to our conversation: I studied the entries below, and I think I meant exactly the same as #112 
As far as I understand this discussion https://wordpress.org/support/topic/missing-image-in-blogposting?replies=1 , Google probably doesnt like a default featured image. Just in case it is of any help, my problem is:
I dont use the image "default"-option in WP (I leave it empty), because it has some "ugly" consequences if I do. This is why I prefer the plugin to pick a(nother) photo that belongs to the individual news article post.
